FROM python
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN pip install faker
RUN python manage.py shell

CMD [ "gunicorn","--bind","0.0.0.0:8000","pollme.wsgi:application"]